name: check out native conda

on:
  push:
    paths-ignore:
      - 'misc/**'


jobs:
  check-it-out:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: configure conda
        run: |
          source "$CONDA/etc/profile.d/conda.sh"
          conda config --set always_yes yes --set changeps1 no
          sudo conda update -q conda
          conda info -a

      - name: test out creating an env
        run: |
          conda create -q -p ./test-env

      - name: try out activation...
        run: |
          source "$CONDA/etc/profile.d/conda.sh"
          conda activate ./test-env
          sudo conda install flake8
          conda list > dontcommitme.txt
          cp dontcommitme.txt misc/${{ matrix.os }}.txt

      - name: commit results
        run: |
          git config --global user.name 'thermokarst'
          git config --global user.email 'thermokarst@users.noreply.github.com'
          git commit -i 'misc/*' -m "CI: ${{ matrix }}"
          git push
