name: check out native conda

on:
  push:
    paths-ignore:
      - 'misc/**'

jobs:
  check-it-out:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: configure conda
        run: |
          source "$CONDA/etc/profile.d/conda.sh"
          conda config --set always_yes yes --set changeps1 no
          sudo conda update -q conda
          conda info -a

      - name: test out creating an env
        run: |
          conda create -q -p ./test-env

      - name: try out activation...
        run: |
          source "$CONDA/etc/profile.d/conda.sh"
          conda activate ./test-env
          sudo conda install flake8
          conda list > dontcommitme.txt
          cp dontcommitme.txt ${{ matrix.os }}.txt

      - name: cache env
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: ${{ matrix.os }}

  commit-the-results:
    runs-on: ubuntu-latest
    needs: check-it-out
    steps:
      - uses: actions/checkout@v2

      - name: fetch envs
        uses: actions/download-artifact@v2
        with:
          path: tmp-envs-dir

      - name: move results to final resting place
        run: |
          mv tmp-envs-dir/ubuntu-latest/* misc/
          mv tmp-envs-dir/macos-latest/* misc/

      - name: commit results
        run: |
          git config --global user.name 'thermokarst'
          git config --global user.email 'thermokarst@users.noreply.github.com'
          git commit \
            misc/ubuntu-latest.txt \
            misc/macos-latest.txt \
            --allow-empty \
            -m "CI: updated envs"
          git push
