name: check out native conda

on: [push]

jobs:
  check-it-out:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: configure conda
        run: |
          source "$CONDA/etc/profile.d/conda.sh"
          hash -r
          conda config \
            --set always_yes yes \
            --set changeps1 no
          echo -e "pkgs_dirs:\n    - $HOME/.conda/pkgs\n" >> $HOME/.condarc
          echo -e "envs_dirs:\n    - $HOME/.conda/envs\n" >> $HOME/.condarc
          cat $HOME/.condarc
          conda update -q conda
          conda info -a

      - name: test out creating an env
        run: conda create -q -p ./test-env

      - name: try out activation...
        run: |
          conda activate ./test-env
          conda list
