name: check out native conda

on: [push]

jobs:
  check-it-out:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: debug conda
        run: $CONDA/bin/conda info

      - name: test out creating an env
        run: $CONDA/bin/conda create -p ./test-env
