name: check out native conda

on: [push]

jobs:
  check-it-out:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: configure conda
        run: |
          source "$CONDA/etc/profile.d/conda.sh"
          conda config --set always_yes yes --set changeps1 no
          echo -e "pkgs_dirs:\n    - $HOME/.conda/pkgs" >> $HOME/.condarc
          echo -e "envs_dirs:\n    - $HOME/.conda/envs" >> $HOME/.condarc
          mkdir -p $HOME/.conda/{pkgs,envs}
          ls -lah $HOME/.conda
          sudo chmod -R 744 $HOME/.conda
          ls -lah $HOME/.conda
          sudo conda update -q conda
          conda info -a

      - name: test out creating an env
        run: |
          conda create -q -p ./test-env

      - name: try out activation...
        run: |
          source "$CONDA/etc/profile.d/conda.sh"
          conda activate ./test-env
          conda install flake8
          conda list
