name: check out native conda

on: [push]

jobs:
  check-it-out:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: debug conda
        run: conda info

      - name: test out creating an env
        run: conda create -p ./test-env

      - name: try out activation...
        run: conda activate ./test-env
